"""Render the main results table (SR / PCS / CFR per track) as LaTeX.

Reads bench_runner/results/METRICS.csv -- the per-run record written by
`recompute_metrics.py --out` -- so the table can never drift from the graded
data. Re-run it after any re-grade:

    python bench_runner/reports/recompute_metrics.py results/<model> --out results/METRICS.csv
    python bench_runner/reports/gen_main_table.py

Both applications are pooled, as in the paper. SR is a mean over graded runs of
a binary per-case verdict; PCS is the mean of the per-case goal fraction and
skips a case whose goal class is empty; CFR is the mean of a binary per-case
verdict over the preservation class.
"""
from __future__ import annotations

import argparse
import csv
import io
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# display order; a model with no runs on a track gets an em-dash there
MODELS = [("claude-opus-5", "Claude Opus 5"),
          ("gpt-5.6", "GPT-5.6"),
          ("gemini-3.7-flash", "Gemini 3.7 Flash"),
          ("claude-sonnet-5", "Claude Sonnet 5"),
          ("gpt-5.6-terra", "GPT-5.6-terra"),
          ("gpt-5.6-luna", "GPT-5.6-luna"),
          ("qwen3.7-plus", "Qwen3.7-Plus"),
          ("qwen3.8-max", "Qwen3.8-Max"),
          ("muse-spark-1.1", "Muse Spark 1.1")]
ARMS = [("1_raw", "none"), ("2_docs", "docs"), ("3_priors", "support")]   # arm DIR names are historical
TRACKS = [("atomic_tasks", "Atomic"), ("reasoning_tasks", "Reasoning"),
          ("long-seq_tasks", "Long-Sequence")]

PREAMBLE = r"""% Generated by bench_runner/reports/gen_main_table.py from
% bench_runner/results/METRICS.csv -- do not hand-edit; regenerate after a re-grade.
\begin{table}[t]
\centering\small
\caption{Success rate (SR), partial completion score (PCS) and collateral-free
rate (CFR), in percent, pooled over the two authoring applications. ``Support''
names the knowledge the agent is given: none, the vendors' official
documentation, or the operational support on top of it. SR counts an unrun case
as a failure; PCS and CFR are means over graded runs, and PCS skips the four
cases whose goal class is empty. Per-run values are released with the
benchmark.}
\label{tab:main_results}
\begin{tabular}{ll rrr rrr rrr}
\toprule
& & \multicolumn{3}{c}{Atomic} & \multicolumn{3}{c}{Reasoning}
& \multicolumn{3}{c}{Long-Sequence} \\
\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-11}
Model & Support & SR & PCS & CFR & SR & PCS & CFR & SR & PCS & CFR \\
\midrule
"""
CLOSE = "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
DASH = "--"


def load(csv_path: Path) -> list[dict]:
    rows = list(csv.DictReader(csv_path.open(encoding="utf-8")))
    for r in rows:
        r["sr"] = r["sr"] == "True"
        r["cfr"] = float(r["cfr"])
        r["pcs"] = float(r["pcs"]) if r["pcs"] else None
    return rows


def cell(runs: list[dict], key: str) -> str:
    if key == "pcs":
        vals = [r["pcs"] for r in runs if r["pcs"] is not None]
        return f"{100 * sum(vals) / len(vals):.1f}" if vals else DASH
    return f"{100 * sum(r[key] for r in runs) / len(runs):.1f}"


def build(rows: list[dict]) -> str:
    out = io.StringIO()
    out.write(PREAMBLE)
    blocks = []
    for model, label in MODELS:
        lines = []
        for arm, arm_label in ARMS:
            cells, present = [], False
            for track, _ in TRACKS:
                runs = [r for r in rows if r["model"] == model
                        and r["track"] == track and r["arm"] == arm]
                if runs:
                    present = True
                    cells += [cell(runs, "sr"), cell(runs, "pcs"), cell(runs, "cfr")]
                else:
                    cells += [DASH, DASH, DASH]
            if present:
                name = label if not lines else ""
                lines.append(f"{name} & {arm_label} & " + " & ".join(cells) + r" \\")
        if lines:
            blocks.append("\n".join(lines))
    out.write(("\n" + r"\addlinespace" + "\n").join(blocks))
    out.write("\n" + CLOSE)
    return out.getvalue()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--metrics", type=Path,
                    default=ROOT / "bench_runner" / "results" / "METRICS.csv")
    ap.add_argument("--out", type=Path, default=ROOT / "table_main_results.tex")
    a = ap.parse_args(argv)
    if not a.metrics.exists():
        ap.error(f"no metrics file at {a.metrics} — run recompute_metrics.py --out first")
    tex = build(load(a.metrics))
    a.out.write_text(tex, encoding="utf-8")
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
